#ifndef _VERSION_H
#define _VERSION_H

#define PROJECT_NAME "SmartDeskLamp"
#define PROJECT_VERSION "0.0.1"
/* #undef PROJECT_VERSION_MAJOR */
/* #undef PROJECT_VERSION_MINOR */
#define PROJECT_VERSION_PATCH "1"
#define VERSION_BUILD_TIME "0.0.1_20230914_10.40.33"

#endif //_VERSION_H
